name: testing my skill

  on:
    push:
      branches:
        - main
      path: *.tf

jobs:
  terraform:
    runs-on:

  steps:
  - name: checkout code
    uses: actions/checkout@v3

  - name: login into aws
    uses: aws-actions/configure-aws-credentials@v4.3.1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-2

  - name: get caller identity2
    run: |
      aws sts get-caller-identity
